WIP; uncached buildpack builds and runs
Signed-off-by: Sam Smith <sesmith177@gmail.com>

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -3,25 +3,38 @@ set -euo pipefail
 
 BUILD_DIR=$1
 CACHE_DIR=$2
+export BUILDPACK_DIR=`dirname $(readlink -f ${BASH_SOURCE%/*})`
 
 GO_VERSION="1.7.5"
-# GO_VERSION="1.8rc3"
+GO_MD5="c9de5bb95790044de676301898e92a1b"
 
-export GOROOT=/tmp/go
-mkdir -p $GOROOT
-URL=https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
+URL=https://buildpacks.cloudfoundry.org/dependencies/go/go${GO_VERSION}.linux-amd64-c9de5bb9.tar.gz
 
 echo "-----> Download go ${GO_VERSION}"
-curl -s -L --retry 15 --retry-delay 2 $URL | tar xz -C $GOROOT --strip-component=1
+curl -s -L --retry 15 --retry-delay 2 $URL -o /tmp/go.tar.gz
+
+DOWNLOAD_MD5=$(md5sum /tmp/go.tar.gz | cut -d ' ' -f 1)
+
+if [[ $DOWNLOAD_MD5 != $GO_MD5 ]]; then
+  echo "       **ERROR** MD5 mismatch: got $DOWNLOAD_MD5 expected $GO_MD5"
+  exit 1
+fi
+
+tar xzf /tmp/go.tar.gz -C /tmp
+
+export GOROOT=/tmp/go
+export GOPATH=$BUILDPACK_DIR
 
 if [ -f $GOROOT/bin/go ]; then
-  export BUILDPACK_DIR=`dirname $(readlink -f ${BASH_SOURCE%/*})`
-  export GOPATH=$BUILDPACK_DIR/.GOPATH
-
-  echo "-----> Run compile.go"
-  (cd $BUILDPACK_DIR && $GOROOT/bin/go build -o bin/compile.out compile.go)
-  $BUILDPACK_DIR/bin/compile.out $BUILD_DIR $CACHE_DIR
+  echo "-----> Running go build compile"
+  output_dir=$(mktemp -d -t compileXXX)
+  $GOROOT/bin/go build -o $output_dir/compile compile
 else
   echo "       **ERROR** Could not download go"
   exit 1
 fi
+
+unset GOOROT
+unset GOPATH
+
+$output_dir/compile $BUILD_DIR $CACHE_DIR
